server:
  port: 8181
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/product?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
